name: DateAnIntervention
options:
  bundleIdPrefix: com.nicemohawk
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  developmentTeam: GYV9U8338K

settings:
  SWIFT_VERSION: "5.9"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  IPHONEOS_DEPLOYMENT_TARGET: "18.0"
  ENABLE_PREVIEWS: YES
  INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
  INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
  INFOPLIST_KEY_UILaunchScreen_Generation: YES
  INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
  GENERATE_INFOPLIST_FILE: YES

targets:
  DateAnIntervention:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - DateAnIntervention
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.nicemohawk.interventiontinder
      INFOPLIST_KEY_CFBundleDisplayName: "Date An Intervention"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: GYV9U8338K
      INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.education
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: DateAnIntervention/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSAllowsArbitraryLoadsInWebContent: false
          NSExceptionDomains:
            api.openai.com:
              NSExceptionAllowsInsecureHTTPLoads: false
              NSIncludesSubdomains: true
              NSExceptionRequiresForwardSecrecy: true
            api.anthropic.com:
              NSExceptionAllowsInsecureHTTPLoads: false
              NSIncludesSubdomains: true
              NSExceptionRequiresForwardSecrecy: true

schemes:
  DateAnIntervention:
    build:
      targets:
        DateAnIntervention: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
